// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdQ_PvWmzLdMUqAniiiZOvEfSp8WIDDUw',
    appId: '1:477949209095:web:07d75a6337f5ea24e058a2',
    messagingSenderId: '477949209095',
    projectId: 'campus-ai-10fd0',
    authDomain: 'campus-ai-10fd0.firebaseapp.com',
    storageBucket: 'campus-ai-10fd0.firebasestorage.app',
    measurementId: 'G-8ZE5D2CX8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvRINYYWf9TqUjRlZ1SDUoYcWU61gnJLg',
    appId: '1:477949209095:android:49566fdad5e0601be058a2',
    messagingSenderId: '477949209095',
    projectId: 'campus-ai-10fd0',
    storageBucket: 'campus-ai-10fd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1OimijJWN7ymBoZsnx7cDT0-KLgEnCWU',
    appId: '1:477949209095:ios:b970fb966ecd819ce058a2',
    messagingSenderId: '477949209095',
    projectId: 'campus-ai-10fd0',
    storageBucket: 'campus-ai-10fd0.firebasestorage.app',
    iosBundleId: 'com.example.campusAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1OimijJWN7ymBoZsnx7cDT0-KLgEnCWU',
    appId: '1:477949209095:ios:b970fb966ecd819ce058a2',
    messagingSenderId: '477949209095',
    projectId: 'campus-ai-10fd0',
    storageBucket: 'campus-ai-10fd0.firebasestorage.app',
    iosBundleId: 'com.example.campusAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdQ_PvWmzLdMUqAniiiZOvEfSp8WIDDUw',
    appId: '1:477949209095:web:9f3c5e1cec8d2acee058a2',
    messagingSenderId: '477949209095',
    projectId: 'campus-ai-10fd0',
    authDomain: 'campus-ai-10fd0.firebaseapp.com',
    storageBucket: 'campus-ai-10fd0.firebasestorage.app',
    measurementId: 'G-CEW5Z5RV7F',
  );

}